# Site settings
title: LOCATION ARTISTRY 
description: Geospatial Devloper and Data Scientist 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Eric M Kerney
user_description: I'm a Geospatial Developer and Data Scientist with years of experience with TypeScript, React and Python. I'm passionate about solving the most challenging societal and business problems with innovative technologies
user_title: Geospatial Developer & Data Scientist 
email: location.artistry@gmail.com 
twitter_username: https://x.com/LocationArtist
github_username:  eKerney
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
